package ru.kuznetsov.qaip.evidence;

/** Stable reasons why relationship evidence was excluded from proof. */
public enum QualificationReason {
    SOURCE_MISMATCH, SNAPSHOT_MISMATCH, MISSING_SOURCE_ENDPOINT,
    MISSING_TARGET_ENDPOINT, UNRESOLVED_SOURCE_ENDPOINT,
    UNRESOLVED_TARGET_ENDPOINT, MISSING_PROVENANCE,
    WRONG_RELATIONSHIP_TYPE, WRONG_SOURCE_ENDPOINT_TYPE,
    WRONG_TARGET_ENDPOINT_TYPE, UNSUPPORTED_NORMALIZATION
}
