package ru.kuznetsov.qaip.simulation.error;

public enum SimulationErrorCode {
    INVALID_SIMULATION_INPUT,
    UNSUPPORTED_MATERIALIZATION_VERSION,
    BASE_MODEL_FINGERPRINT_MISMATCH,
    MATERIALIZATION_MISSING,
    MATERIALIZATION_UNKNOWN_TASK,
    MATERIALIZATION_DUPLICATE_TASK,
    MATERIALIZATION_PAYLOAD_INVALID,
    MATERIALIZATION_INVALID_NODE_ID,
    MATERIALIZATION_NODE_ID_COLLISION,
    MATERIALIZATION_NODE_TYPE_MISMATCH,
    TARGET_NODE_MISSING,
    TARGET_NODE_TYPE_MISMATCH,
    UNSUPPORTED_IMPACT_CHANGE,
    INVALID_CANDIDATE_MODEL_SHAPE,
    RELATIONSHIP_ID_COLLISION,
    DUPLICATE_LOGICAL_RELATIONSHIP,
    CANDIDATE_MODEL_VALIDATION_FAILED
}
