package ru.kuznetsov.qaip.evidencegovernance.fingerprint.semantic;
import java.util.Objects;
/** Closed active rejection taxonomy plus exhaustive disposition of all historical categories. */
public final class ManifestCompositionRejectionV1 extends IllegalArgumentException {
 private final Code code; public ManifestCompositionRejectionV1(Code c){super(Objects.requireNonNull(c).name());code=c;}public Code code(){return code;}
 public enum Code { UNSUPPORTED_MANIFEST_CONTRACT, SCENARIO_COUNT_MISMATCH, SCENARIO_DECLARATION_SUBSTITUTION }
 public enum HistoricalCode { STRUCTURALLY_UNADMITTED_MANIFEST,SCENARIO_SEMANTIC_UNAVAILABLE,SCENARIO_ATTESTATION_MISMATCH,
  SCENARIO_MANIFEST_OCCURRENCE_MISMATCH,SCENARIO_AUTHORITY_MISMATCH,SCENARIO_COUNT_MISMATCH,SCENARIO_POSITION_MISMATCH,
  SCENARIO_DECLARATION_SUBSTITUTION,UNSUPPORTED_MANIFEST_CONTRACT }
 public enum Disposition { CLOSED_BY_VERIFIED_MANIFEST,MANIFEST_UNAVAILABLE_DECISION,CLOSED_BY_CHILD_PROOF_REVALIDATION,
  ACTIVE_SCENARIO_COUNT_MISMATCH,ACTIVE_SCENARIO_DECLARATION_SUBSTITUTION,ACTIVE_UNSUPPORTED_MANIFEST_CONTRACT }
 public static Disposition disposition(HistoricalCode c){return switch(Objects.requireNonNull(c)){
  case STRUCTURALLY_UNADMITTED_MANIFEST->Disposition.CLOSED_BY_VERIFIED_MANIFEST;
  case SCENARIO_SEMANTIC_UNAVAILABLE->Disposition.MANIFEST_UNAVAILABLE_DECISION;
  case SCENARIO_ATTESTATION_MISMATCH,SCENARIO_MANIFEST_OCCURRENCE_MISMATCH,SCENARIO_AUTHORITY_MISMATCH,SCENARIO_POSITION_MISMATCH->Disposition.CLOSED_BY_CHILD_PROOF_REVALIDATION;
  case SCENARIO_COUNT_MISMATCH->Disposition.ACTIVE_SCENARIO_COUNT_MISMATCH;
  case SCENARIO_DECLARATION_SUBSTITUTION->Disposition.ACTIVE_SCENARIO_DECLARATION_SUBSTITUTION;
  case UNSUPPORTED_MANIFEST_CONTRACT->Disposition.ACTIVE_UNSUPPORTED_MANIFEST_CONTRACT;};}
}
