package ru.kuznetsov.qaip.evidencegovernance.fingerprint.semantic;

/** Closed Stage-3 integrity taxonomy frozen by the Scenario identity-group V1 contract. */
public enum ScenarioOccurrenceIntegrityRejectionV1 {
    PARENT_SCENARIO_IDENTITY_DISAGREEMENT, OCCURRENCE_COMPOSITION_REQUEST_MISMATCH,
    PHASE_ARRAY_STEP_DISAGREEMENT, STEP_IDENTITY_MISMATCH, STEP_PHASE_MISMATCH,
    STEP_ORDINAL_MISMATCH, STEP_COUNT_MISMATCH, STEP_POSITION_MISMATCH, STEP_TEXT_MISMATCH,
    STEP_ATTESTATION_INPUT_FINGERPRINT_MISMATCH, OPERATION_OWNERSHIP_MISMATCH,
    OPERATION_DATUM_PROFILE_MISMATCH, OPERATION_METHOD_PATH_MISMATCH,
    OPERATION_ATTESTATION_INPUT_FINGERPRINT_MISMATCH, BUSINESS_RULE_OWNERSHIP_MISMATCH,
    BUSINESS_RULE_AUTHORITY_KEY_SCHEME_MISMATCH, BUSINESS_RULE_COUNT_MISMATCH,
    BUSINESS_RULE_ORDER_POSITION_MISMATCH, BUSINESS_RULE_ATTESTATION_INPUT_FINGERPRINT_MISMATCH,
    INCOMPLETE_COMPOSITION_INPUT, LEAF_FINGERPRINT_SUBSTITUTION,
    SCENARIO_INPUT_FINGERPRINT_SUBSTITUTION
}
