package ru.kuznetsov.qaip.impact.service;

public enum ImpactAnalysisErrorCode {
    DUPLICATE_ROADMAP_TASK_ID,
    UNKNOWN_EXECUTION_TASK,
    DUPLICATE_EXECUTION_TASK,
    ROADMAP_TASK_NOT_SCHEDULED,
    INVALID_EXECUTION_WAVE,
    UNSUPPORTED_REMEDIATION_TASK_TYPE,
    INCONSISTENT_INPUT
}
